rm -rf ./hailort/cmake/external/dotwriter/.git
rm -rf ./hailort/cmake/external/readerwriterqueue/.git
rm -rf ./hailort/cmake/external/benchmark/.git
rm -rf ./hailort/cmake/external/pybind11/.git
rm -rf ./hailort/cmake/external/catch2/.git
rm -rf ./hailort/cmake/external/json/.git
rm -rf ./hailort/cmake/external/spdlog/.git
rm -rf ./hailort/cmake/external/pevents/.git
rm -rf ./hailort/external/protobuf/third_party/benchmark/.git
rm -rf ./hailort/external/protobuf/third_party/googletest/.git
rm -rf ./hailort/cmake/external/benchmark/.github
rm -rf ./hailort/cmake/external/pybind11/.github
rm -rf ./hailort/cmake/external/catch2/.github
rm -rf ./hailort/cmake/external/json/.github
rm -rf ./hailort/cmake/external/pevents/.github
rm -rf ./hailort/external/protobuf/.git
rm -rf ./hailort/external/protobuf/.github
rm -rf ./hailort/external/CLI11/.git
rm -rf ./hailort/external/CLI11/.github
rm -rf .git
rm -rf ./build
rm -rf ./hailort/libhailort/examples/build
rm -rf ./hailort/pre_build/build
rm -rf ./hailort/pre_build/install
rm -rf ./hailort/pre_build/external/build/

